name: Render Keep Awake

on:
  schedule:
    - cron: '5,15,25,35,45,55 * * * *'
  workflow_dispatch:

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    env:
      TARGET_URL: ${{ secrets.RENDER_URL }}

    steps:
      - name: 서버 깨우기
        run: |
          if [ -z "$TARGET_URL" ]; then
            echo "TARGET_URL is empty. Check secrets.RENDER_URL"
            exit 1
          fi

          echo "Pinging Render server..."
          curl -fsS -o /dev/null -w "HTTP Status: %{http_code}\n" "$TARGET_URL"


# 주의
# Render 무료 티어는 한 달에 750시간의 가동 시간을 줍니다.
# 한 달(31일)을 24시간 풀가동하면 744시간이 소요됩니다.

# TARGET_URL: ${{ secrets.RENDER_URL }} 은 
# 개인(본인소유) GitHub 저장소의 Settings > Secrets에 가서 RENDER_URL이라는 이름으로 https:// 본인 URL .onrender.com을 등록해야 합니다.
# ( 별도의 개인 저장소 필요 , 예시 https://github.com/ 유저명 / 리포명 /settings/secrets/actions 에서 Repository secrets ->  new Repository secrets )

